// <auto-generated />
using System;
using ChristmasAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChristmasAPI.Migrations
{
    [DbContext(typeof(PiContext))]
    [Migration("20191030183842_AddUserCorrelations")]
    partial class AddUserCorrelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ChristmasAPI.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ChristmasAPI.Models.Family");
                });

            modelBuilder.Entity("ChristmasAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ExchangeUserId");

                    b.Property<int>("FamilyId");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int?>("SpouseId");

                    b.HasKey("Id");

                    b.ToTable("ChristmasAPI.Models.User");
                });
#pragma warning restore 612, 618
        }
    }
}
