// <auto-generated />
using System;
using ChristmasAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChristmasAPI.Migrations
{
    [DbContext(typeof(PiContext))]
    partial class PiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ChristmasAPI.Models.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("ChristmasAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ExchangeUserId");

                    b.Property<int>("FamilyId");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Last")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int?>("SpouseId");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeUserId")
                        .IsUnique();

                    b.HasIndex("FamilyId");

                    b.HasIndex("SpouseId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("ChristmasAPI.Models.User", b =>
                {
                    b.HasOne("ChristmasAPI.Models.User", "ExchangeUser")
                        .WithOne()
                        .HasForeignKey("ChristmasAPI.Models.User", "ExchangeUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChristmasAPI.Models.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChristmasAPI.Models.User", "Spouse")
                        .WithOne()
                        .HasForeignKey("ChristmasAPI.Models.User", "SpouseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
